jobpotal/urls.py
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'',include('portfolio.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

portfolio/models.py
from __future__ import unicode_literals
from django.db import models
from django.contrib.auth.models import BaseUserManager, AbstractBaseUser, PermissionsMixin


class MyUserManager(BaseUserManager):
    def create_user(self, email, username, user_type, first_name, last_name, contact_number, password=None):

        if not email:
            raise ValueError('Users must have an email address')

        user = self.model(
            email=self.normalize_email(email),
            user_type=user_type,
            username=username,
            contact_number=contact_number,
            first_name=first_name,
            last_name=last_name
        )

        if password:
            user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, username, email, user_type, first_name, last_name, contact_number, password):

        user = self.create_user(email=email,
                                password=password,
                                user_type=user_type,
                                username=username,
                                contact_number=contact_number,
                                first_name=first_name,
                                last_name=last_name
                                )
        user.is_admin = True
        user.is_superuser = True
        user.save(using=self._db)
        return user


class MyUser(AbstractBaseUser, PermissionsMixin):
    username = models.CharField(max_length=30, default='user')
    email = models.EmailField(verbose_name='email address', max_length=255, unique=True, db_index=True,)
    user_type = models.CharField(max_length=30, choices={
        ("A", "Applicant"),
        ("E", "Employer"),
        }, default='A')
    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)
    first_name = models.CharField(max_length=200, blank=True, null=True)
    last_name = models.CharField(max_length=200, blank=True, null=True)
    contact_number = models.CharField(max_length=13, blank=True, null=True)
    date_joined = models.DateTimeField(auto_now_add=True)

    objects = MyUserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['first_name','last_name','contact_number']

    def get_full_name(self):
        full_name = '%s %s' % (self.first_name, self.last_name)
        return full_name.strip()

    def get_short_name(self):
        return self.first_name

    def get_email(self):
        return self.email

    def __unicode__ (self):
        return self.email

    @property
    def is_staff(self):
        return self.is_admin


class BiodataModel(models.Model):

    Status = [
        ('m','Married'),
        ('s','Single'),
        ('d','Divorced'),
        ('w','Widowed')
    ]

    Gender = [
        ('m','Male'),
        ('f','Female')
    ]

    user = models.ForeignKey(MyUser, on_delete=models.CASCADE)
    fathername = models.CharField(max_length=200, null=True, blank=True)
    dob = models.DateField(null=True, blank=True)
    marital_status = models.CharField(max_length=10, choices=Status, null=True, blank=True)
    gender = models.CharField(max_length=2, choices=Gender, null=True, blank=True)
    qualification = models.CharField(max_length=1000, null=True, blank=True)
    address = models.CharField(max_length=200, null=True, blank=True)
    pincode = models.CharField(max_length=200, null=True, blank=True)
    old_erp_esic_numbr = models.CharField(max_length=200, null=True, blank=True)
    bank_acnt = models.CharField(max_length=200, null=True, blank=True)
    ifsc_code = models.CharField(max_length=200, null=True, blank=True)
    police_station = models.CharField(max_length=200, null=True, blank=True)
    idnty_mark = models.CharField(max_length=200, null=True, blank=True)
    dateofjoining = models.DateField(null=True, blank=True)
    experience = models.CharField(max_length=1000, null=True, blank=True)
    preffered_jobs = models.CharField(max_length=500, null=True, blank=True)
    pic = models.ImageField(upload_to='profile')
    emailverified = models.BooleanField(default=False)
    lastupdated = models.DateTimeField(auto_now_add=True)
    deleted = models.BooleanField(default=False)


class JobsModel(models.Model):

    Time = [
        ('a','1 yr'),
        ('b','2 yr'),
        ('c','3 yr'),
        ('d','4 yr'),
        ('e','5 yr')
    ]

    ExperienceType = [
        ('entry','Entry Level'),
        ('mid','Mid Level'),
        ('senior','Mid-Senior Level'),
        ('top','Top Level')
    ]

    jobtitle = models.CharField(max_length=200, null=True, blank=True)
    description = models.CharField(max_length=500, null=True, blank=True)
    department = models.CharField(max_length=200, null=True, blank=True)
    about = models.CharField(max_length=500, null=True, blank=True)
    location = models.CharField(max_length=200, null=True, blank=True)
    qualification = models.CharField(max_length=200, null=True, blank=True)
    experience = models.CharField(max_length=200, choices=ExperienceType, null=True, blank=True)
    vacancies = models.IntegerField(null=True, blank=True)
    salary = models.CharField(max_length=200, null=True, blank=True)
    addedon = models.DateTimeField(auto_now_add=True)
    lastdate = models.DateField(null=True, blank=True)
    doj = models.DateField(null=True, blank=True)
    interview_process = models.CharField(max_length=200, null=True, blank=True)
    interview_venue = models.CharField(max_length=200, null=True, blank=True)
    bondtime = models.CharField(max_length=50, choices=Time, null=True, blank=True)
    dept_logo = models.FileField(upload_to='logo', null=True)
    deleted = models.BooleanField(default=False)


class JobsApplied(models.Model):
    jobid = models.ForeignKey(JobsModel, on_delete=models.CASCADE)
    userid = models.ForeignKey(MyUser, on_delete=models.CASCADE)
    applied_on = models.DateTimeField(auto_now_add=True)


class FormUANbased(models.Model):
    user = models.ForeignKey(MyUser, on_delete=models.CASCADE)
    UAN =  models.CharField(max_length=50, null=True, blank=True)
    leaving_date = models.DateField(null=True, blank=True)
    PAN = models.CharField(max_length=50, null=True, blank=True)
    purpose = models.CharField(max_length=200, null=True, blank=True)
    advance_amount = models.CharField(max_length=200, null=True, blank=True)
    agency_address = models.CharField(max_length=200, null=True, blank=True)
    address = models.CharField(max_length=200, null=True, blank=True)
    PIN = models.CharField(max_length=200, null=True, blank=True)

class Form10c(models.Model):
    user = models.ForeignKey(MyUser, on_delete=models.CASCADE)
    claimant_name = models.CharField(max_length=50, null=True, blank=True)
    father_name = models.CharField(max_length=50, null=True, blank=True)
    husband_name = models.CharField(max_length=50, null=True, blank=True)
    old_Estt_name = models.CharField(max_length=50, null=True, blank=True)
    old_Estt_address = models.CharField(max_length=50, null=True, blank=True)
    old_Estt_region = models.CharField(max_length=50, null=True, blank=True)
    old_Estt_code_no = models.CharField(max_length=50, null=True, blank=True)
    old_Estt_Acnt_no = models.CharField(max_length=50, null=True, blank=True)
    leaving_reason = models.CharField(max_length=50, null=True, blank=True)
    address = models.CharField(max_length=200, null=True, blank=True)
    PIN = models.CharField(max_length=200, null=True, blank=True)
    family_name = models.CharField(max_length=200, null=True, blank=True)
    family_dob = models.CharField(max_length=200, null=True, blank=True)
    family_relation = models.CharField(max_length=200, null=True, blank=True)
    nomine = models.CharField(max_length=200, null=True, blank=True)
    member_death_date = models.CharField(max_length=200, null=True, blank=True)
    claminant_name = models.CharField(max_length=200, null=True, blank=True)
    claminant_relation = models.CharField(max_length=200, null=True, blank=True)
    SB_Acnt_no = models.CharField(max_length=200, null=True, blank=True)
    SB_BankName = models.CharField(max_length=200, null=True, blank=True)
    SB_BankBranch = models.CharField(max_length=200, null=True, blank=True)
    SB_BankIFSC = models.CharField(max_length=200, null=True, blank=True)
    SB_BankAddress = models.CharField(max_length=200, null=True, blank=True)

class Form19c_Old(models.Model):
    user = models.ForeignKey(MyUser, on_delete=models.CASCADE)
    father_name = models.CharField(max_length=100, null=True, blank=True)
    husband_name = models.CharField(max_length=100, null=True, blank=True)
    factory_address = models.CharField(max_length=200, null=True, blank=True)
    PF_Acnt_no = models.CharField(max_length=50, null=True, blank=True)
    UAN = models.CharField(max_length=50, null=True, blank=True)
    doj = models.DateField(null=True, blank=True)
    leaving_date = models.DateField(null=True, blank=True)
    leaving_reason = models.CharField(max_length=200, null=True, blank=True)
    PAN = models.CharField(max_length=50, null=True, blank=True)
    address = models.CharField(max_length=200, null=True, blank=True)
    PIN = models.CharField(max_length=50, null=True, blank=True)
    saving_Acnt_bo = models.CharField(max_length=50, null=True, blank=True)
    saving_bank = models.CharField(max_length=50, null=True, blank=True)
    saving_bank_address = models.CharField(max_length=200, null=True, blank=True)
    saving_bank_IFSC = models.CharField(max_length=20, null=True, blank=True)

portfolio/forms.py
from django import forms
from portfolio.models import BiodataModel, JobsModel
from .models import MyUser
from django.conf import settings


class UserCreationForm(forms.ModelForm):
    email = forms.EmailField(max_length=255, widget=forms.EmailInput(attrs={'class': 'form-control',
                             'placeholder': 'Email Address'}))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control',
                                'placeholder': 'Create Password'}))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control',
                                'placeholder': 'Re-enter Password'}), error_messages={'required': "Please enter your password"})
    first_name = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'First Name'}))
    last_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Last Name'}))
    contact_number = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Contact Number'}))

    user_type = forms.ChoiceField(choices={
        ("A", "Applicant"),
        ("E", "Employer"),
        }, widget=forms.RadioSelect(), initial="A")

    class Meta:
        model = MyUser
        fields = ('email', 'user_type', 'first_name', 'last_name', 'contact_number')

    def __init__(self, *args, **kwargs):

        super(UserCreationForm, self).__init__(*args, **kwargs)
        self.fields['email'].label = False
        self.fields['password1'].label = False
        self.fields['password2'].label = False

    def clean_email(self):
        email = self.cleaned_data['email']
        #self.cleaned_data['username'] = email
        if MyUser.objects.filter(email=email).exists():
            raise forms.ValidationError("Email %s is already in use" % (email))
        return email

    def clean_password2(self):
        """Checks two password entries match.
        """
        cleaned_data = super(UserCreationForm, self).clean() #to see the password validation
        password1 = self.cleaned_data.get('password1')
        password2 = self.cleaned_data.get('password2')
        # if len(password1) <= 4 or len(password2) <= 4:
        #     raise forms.ValidationError("Password must be at least 5 characters long")
        if password1 and password2:
            if password1 != password2:
                raise forms.ValidationError("Passwords don't match")
                # del cleaned_data["password1"]  #to delete the invalid password, not necessary
                # del cleaned_data["password2"]
        return password2

    def save(self, commit=True):
        """Saves the provided password in hashed format.
        """
        user = super(UserCreationForm, self).save(commit=False)
        # get the user object first, then add password, then save
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.is_active = True
            user.save()
        return user


class LoginForm(forms.Form):
    email = forms.EmailField(max_length=255, widget=forms.EmailInput(attrs={'class': 'form-control',
                             'placeholder': 'Your email address'}), error_messages={'required': "Please enter your email id"})
                           # widget=forms.widgets.TextInput
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control',
                               'placeholder': 'Your password'}), error_messages={'required': "Please enter your password"})
                            # widget=forms.widgets.PasswordInput

    class Meta:
        fields = ['email', 'password']

    def __init__(self, *args, **kwargs):
        super(LoginForm, self).__init__(*args, **kwargs)
        self.fields['email'].label = False
        self.fields['password'].label = False


class BiodataForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(BiodataForm, self).__init__(*args, **kwargs)
        self.fields['dob'].input_formats = settings.DATE_INPUT_FORMATS
        self.fields['dateofjoining'].input_formats = settings.DATE_INPUT_FORMATS
        self.fields['marital_status'].choices = BiodataModel.Status
        self.fields['gender'].choices = BiodataModel.Gender

    class Meta:
        model = BiodataModel
        exclude = ['pic','emailverified','deleted']

        widgets = {
            'fathername': forms.TextInput(attrs={'class': 'form-control','required':'true'}),
            'dob': forms.DateInput(attrs={'class': 'form-control','id': 'datepicker1','required':'true'}),
            'marital_status': forms.Select(attrs={'class': 'form-control'}),
            'qualification': forms.Textarea(attrs={'class': 'form-control','rows': 5}),
            'address': forms.Textarea(attrs={'class': 'form-control', 'rows': 3, 'required':'true'}),
            'old_erp_esic_numbr': forms.TextInput(attrs={'class': 'form-control'}),
            'bank_acnt': forms.TextInput(attrs={'class': 'form-control'}),
            'ifsc_code': forms.TextInput(attrs={'class': 'form-control'}),
            'police_station': forms.TextInput(attrs={'class': 'form-control'}),
            'idnty_mark': forms.TextInput(attrs={'class': 'form-control'}),
            'dateofjoining': forms.DateInput(attrs={'class': 'form-control','id': 'datepicker2'}),
            'experience': forms.Textarea(attrs={'class': 'form-control', 'rows': 5}),
            'preffered_jobs': forms.Textarea(attrs={'class': 'form-control', 'rows': 5}),
            'gender': forms.Select(attrs={'class': 'form-control'})
        }


class ImageForm(forms.ModelForm):
    class Meta:
        model = BiodataModel
        fields = ['pic',]

        widgets = {
            'pic': forms.FileInput()
        }


class JobsForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(JobsForm, self).__init__(*args, **kwargs)
        self.fields['bondtime'].choices = JobsModel.Time
        self.fields['experience'].choices = JobsModel.ExperienceType

    class Meta:
        model = JobsModel
        fields = '__all__'

        widgets = {
            'jobtitle': forms.TextInput(attrs={'class': 'form-control', 'required': 'true'}),
            'description': forms.Textarea(attrs={'class': 'form-control', 'required': 'true', 'rows': 5}),
            'department': forms.TextInput(attrs={'class': 'form-control', 'required': 'true'}),
            'location': forms.TextInput(attrs={'class': 'form-control', 'required': 'true'}),
            'qualification': forms.Textarea(attrs={'class': 'form-control', 'required': 'true', 'rows': 5}),
            'experience': forms.Select(attrs={'class': 'form-control', 'required': 'true'}),
            'vacancies': forms.NumberInput(attrs={'class': 'form-control'}),
            'salary': forms.TextInput(attrs={'class': 'form-control', 'required': 'true'}),
            'lastdate': forms.DateInput(attrs={'class': 'form-control', 'id': 'datepicker1', 'required': 'true'}),
            'interview_process': forms.Textarea(attrs={'class': 'form-control', 'rows': 5}),
            'interview_venue': forms.TextInput(attrs={'class': 'form-control', 'required': 'true'}),
            'doj': forms.DateInput(attrs={'class': 'form-control', 'id': 'datepicker2', 'required': 'true'}),
            'bondtime': forms.Select(attrs={'class': 'form-control'}),
            'about': forms.Textarea(attrs={'class': 'form-control', 'rows': 5}),
            'dept_logo': forms.FileInput()
        }

templates/imageupload.html
<div><span class="close lightbox_close" onclick="closeModal()">&times;</span></div>
<div class="lightbox_content">

<h3 class="text-center">Upload your recent photo</h3>

    <div style="margin-top:30px;" class="col-md-12">
        <form id="imgform" method="post" action="/imgupload/" enctype="multipart/form-data">
            {% csrf_token %}

            <div class="form-group"><input id="id_pic" name="pic" type="file"></div>
            <div class="form-group" id="errmsg" style="display: none;">
                <p style="margin-bottom: 0px !important;color: red;">Image exceeds the maximum size(50Kb) <br> Please upload less than 50kb Image</p>
            </div>
            <div class="form-group" style="margin-top: 6px;"><button id="imbtn" disabled="" class="btn btn-primary" style="width: 120px;" type="submit">Save</button></div>

        </form>
    </div>

</div>
<script src="/static/jobsite/js/img.js"></script>
<script type="text/javascript">
    $(function () {
        $("#id_pic").on('change', function () {
            if (typeof ($("#id_pic")[0].files) != "undefined") {
                var size = parseFloat($("#id_pic")[0].files[0].size / 1024).toFixed(2);
                if(size > 50){
                    $('#errmsg').show();
                    $('#lightbox_content').removeClass('lightbox_width').addClass('lightbox_errorwidth');
                }
                else{
                    $('#imbtn').removeAttr('disabled');
                    $('#errmsg').hide();
                    $('#lightbox_content').removeClass('lightbox_errorwidth').addClass('lightbox_width');
                }
            } else {
                alert("This browser does not support HTML5.");
            }
        });
    });
</script>

templates/signup.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="author" content="Theme Region">
   	<meta name="description" content="">

    <title>Jobs | Job Portal / Job Board HTML Template</title>

    <!-- CSS -->
    <link rel="stylesheet" href="/static/jobsite/css/bootstrap.min.css" >
    <link rel="stylesheet" href="/static/jobsite/css/font-awesome.min.css">
	<link rel="stylesheet" href="/static/jobsite/css/icofont.css">
    <link rel="stylesheet" href="/static/jobsite/css/slidr.css">
    <link rel="stylesheet" href="/static/jobsite/css/main.css">
	<link rel="stylesheet" href="/static/jobsite/css/jobsite.css">
	<link id="preset" rel="stylesheet" href="/static/jobsite/css/presets/preset1.css">
    <link rel="stylesheet" href="/static/jobsite/css/responsive.css">
    <link rel="stylesheet" href="/static/jQueryValidationEngine/css/validationEngine.jquery.css">
    <link rel="stylesheet" href="/static/font-awesome/css/font-awesome.min.css">

	<!-- font -->
	<link href='https://fonts.googleapis.com/css?family=Ubuntu:400,500,700,300' rel='stylesheet' type='text/css'>
	<link href='https://fonts.googleapis.com/css?family=Signika+Negative:400,300,600,700' rel='stylesheet' type='text/css'>

	<!-- icons -->
	<link rel="icon" href="/static/jobsite/images/ico/favicon.ico">
    <link rel="apple-touch-icon" sizes="144x144" href="/static/jobsite/images/ico/apple-touch-icon-144-precomposed.png">
    <link rel="apple-touch-icon" sizes="114x114" href="/static/jobsite/images/ico/apple-touch-icon-114-precomposed.png">
    <link rel="apple-touch-icon" sizes="72x72" href="/static/jobsite/images/ico/apple-touch-icon-72-precomposed.html">
    <link rel="apple-touch-icon" sizes="57x57" href="/static/jobsite/images/ico/apple-touch-icon-57-precomposed.png">
    <!-- icons -->

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    <!-- Template Developed By ThemeRegion -->
  </head>
  <body>
	<!-- header -->
	<header id="header" class="clearfix">
		<!-- navbar -->
		<nav class="navbar navbar-default">
			<div class="container">
				<!-- navbar-header -->
				<div class="navbar-header">
					<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse">
					<span class="sr-only">Toggle navigation</span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					</button>
					<a class="navbar-brand" href="/"><img class="img-responsive" src="/static/jobsite/images/logo.png" alt="Logo"></a>
				</div>
				<!-- /navbar-header -->

				<div class="navbar-left">
					<div class="collapse navbar-collapse" id="navbar-collapse">
						<ul class="nav navbar-nav">
							<li><a href="index-2.html">Home</a></li>
							<li><a href="/jobs/">Job list</a></li>
							{% if request.user.is_authenticated and request.user.user_type == 'A' %}
							<li><a href="/appliedjobs/">Applied Jobs</a></li>
							{% endif %}
							{% if request.user.is_authenticated and request.user.user_type == 'A' %}
							<li><a href="/biodata/{{request.user.id}}">Biodata</a></li>
							{% endif %}
							{% if request.user.is_superuser %}
							<li class="dropdown"><a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown">Admin<span class="caret"></span></a>
								<ul class="dropdown-menu">
									<li><a href="/users/">Users</a></li>
									<li><a href="/admin/">Administration</a></li>
									<li><a href="post.html">Job Post</a></li>
									<li><a href="edit-resume.html">Edit Resume</a></li>
									<li><a href="profile-details.html">profile Details</a></li>
									<li><a href="bookmark.html">Bookmark</a></li>
									<li><a href="applied-job.html">Applied Job</a></li>
									<li><a href="delete-account.html">Close Account</a></li>
									<li><a href="signup.html">Job Signup</a></li>
									<li><a href="/login/">Job Signin</a></li>
								</ul>
							</li>
							{% endif %}
						</ul>
					</div>
				</div><!-- navbar-left -->

				<!-- nav-right -->
				<div class="nav-right">
					<ul class="sign-in">
						<li><i class="fa fa-user"></i></li>
						<li><a href="/signin/">Sign In</a></li>
						<li><a href="/signup/">Register</a></li>
					</ul><!-- sign-in -->
					{% if request.user.user_type == 'E' %}
					<a href="/postjob/" class="btn">Post Your Job</a>
					{% endif %}
				</div>
				<!-- nav-right -->
			</div><!-- container -->
		</nav><!-- navbar -->
	</header><!-- header -->

	<section class="job-bg user-page">
		<div class="container">
			<div class="row text-center">
				<!-- user-login -->
				<div class="col-sm-8 col-sm-offset-2 col-md-6 col-md-offset-3">
					<div class="user-account job-user-account">
						<h2>Create An Account</h2>
					 	<div class="col-lg-12 col-md-12">
						{% if messages %}
							{% for message in messages %}
								<div class="alert alert-success">
									<button type="button" class="close" data-dismiss="alert">x</button>
									{{ message }}
								</div>
							{% endfor %}
						{% endif %}
						</div>

							<div class="tab-content">
								<div role="tabpanel" class="tab-pane active" id="find-job">
									<form class="form" method="post" action="">
                                        {% csrf_token %}
										<div style="margin-bottom: 28px; !important" class="form-group">
											<ul style="display:inline-flex;" id="id_user_type">
												<li style="margin-right:30px;">
													<label class="radio-inline" for="id_user_type_0"><input style="margin-top: -11px !important;" checked="checked" id="id_user_type_0" name="user_type" type="radio" value="A"><b> Applicant</b></label>
												</li>
												<li>
													<label class="radio-inline" for="id_user_type_1"><input style="margin-top: -11px !important;" id="id_user_type_1" name="user_type" type="radio" value="E"><b> Employer</b></label>
												</li>
											</ul>

										</div>
										<div class="form-group">
											<input class="form-control validate[required]" id="id_first_name" name="first_name" placeholder="First Name" type="text">
										</div>
										<div class="form-group">
											<input class="form-control validate[required]" id="id_last_name" name="last_name" placeholder="Last Name" type="text">
										</div>
										<div class="form-group">
											<input class="form-control validate[required,custom[phone],maxSize[13]]" id="id_contact_number" name="contact_number" placeholder="Contact Number" type="text">
										</div>
										<div class="form-group">
											<input class="form-control validate[custom[email],required]" id="id_email" maxlength="255" name="email" placeholder="Email Address" type="email">
										</div>
										<div class="form-group">
											<input class="form-control validate[required,minSize[6]]" id="id_password1" name="password1" placeholder="Create Password" type="password">
										</div>
										<div class="form-group">
											<input class="form-control validate[required,equals[id_password1]]" id="id_password2" name="password2" placeholder="Re-enter Password" type="password">
										</div>

										<button id="signupbtn" type="submit" class="btn">Registration</button>
									</form>
								</div>
							</div>
					</div>
				</div><!-- user-login -->
			</div><!-- row -->
		</div><!-- container -->
	</section><!-- signup-page -->

	<!-- footer -->
	<footer id="footer" class="clearfix">
		<!-- footer-top -->
		<section class="footer-top clearfix">
			<div class="container">
				<div class="row">
					<!-- footer-widget -->
					<div class="col-sm-3">
						<div class="footer-widget">
							<h3>Quik Links</h3>
							<ul>
								<li><a href="#">About Us</a></li>
								<li><a href="#">Contact Us</a></li>
								<li><a href="#">Careers</a></li>
								<li><a href="#">All Cities</a></li>
								<li><a href="#">Help & Support</a></li>
								<li><a href="#">Advertise With Us</a></li>
							</ul>
						</div>
					</div><!-- footer-widget -->

					<!-- footer-widget -->
					<div class="col-sm-3">
						<div class="footer-widget">
							<h3>How to sell fast</h3>
							<ul>
								<li><a href="#">How to sell fast</a></li>
								<li><a href="#">Membership</a></li>
								<li><a href="#">Banner Advertising</a></li>
								<li><a href="#">Promote your ad</a></li>
								<li><a href="#">Jobs Delivers</a></li>
								<li><a href="#">FAQ</a></li>
							</ul>
						</div>
					</div><!-- footer-widget -->

					<!-- footer-widget -->
					<div class="col-sm-3">
						<div class="footer-widget social-widget">
							<h3>Follow us on</h3>
							<ul>
								<li><a href="#"><i class="fa fa-facebook-official"></i>Facebook</a></li>
								<li><a href="#"><i class="fa fa-twitter-square"></i>Twitter</a></li>
								<li><a href="#"><i class="fa fa-google-plus-square"></i>Google+</a></li>
								<li><a href="#"><i class="fa fa-youtube-play"></i>youtube</a></li>
							</ul>
						</div>
					</div><!-- footer-widget -->

					<!-- footer-widget -->
					<div class="col-sm-3">
						<div class="footer-widget news-letter">
							<h3>Newsletter</h3>
							<p>Jobs is Worldest leading Portal platform that brings!</p>
							<!-- form -->
							<form action="#">
								<input type="email" class="form-control" placeholder="Your email id">
								<button type="submit" class="btn btn-primary">Sign Up</button>
							</form><!-- form -->
						</div>
					</div><!-- footer-widget -->
				</div><!-- row -->
			</div><!-- container -->
		</section><!-- footer-top -->

		<div class="footer-bottom clearfix text-center">
			<div class="container">
				<p>Copyright &copy; <a href="#">Jobs</a> 2017. Developed by <a href="javascript:void(0);">Aditya Sharma and Rochan Sharma</a></p>
			</div>
		</div><!-- footer-bottom -->
	</footer><!-- footer -->

    <!-- JS -->
    <script src="/static/jobsite/js/jquery.min.js"></script>
    <script src="/static/jobsite/js/bootstrap.min.js"></script>
    <script src="/static/jobsite/js/price-range.js"></script>
    <script src="/static/jobsite/js/main.js"></script>
	<script src="/static/jobsite/js/switcher.js"></script>
	<script src="/static/jobsite/js/jobsite.js"></script>
	<script src="/static/jQueryValidationEngine/js/jquery.validationEngine.js"></script>
	<script src="/static/jQueryValidationEngine/js/jquery.validationEngine-en.js"></script>
	<script src="/static/JqueryAutoComplete/js/jqueryautocomplete.js"></script>

  </body>

<!-- Mirrored from demo.themeregion.com/jobs-updated/signup.html by HTTrack Website Copier/3.x [XR&CO'2014], Tue, 31 Jan 2017 19:26:06 GMT -->
</html>